CC=g++ -g
VPATH=
CXXFLAGS=-lgcc_s 
INCLUDE=./src:./headers
MEX=$(CC) $(LDFLAGS)
MCC=$(CC) -c
EXE=main

SRC=$(wildcard *.cpp ./src/*.cpp)
OBJ=$(patsubst %.cpp,%.o,$(notdir $(SRC)))
EXE=main

all:$(EXE)

$(EXE): ${OBJ}
   $(MEX) $^ -o $@ $(INCLUDE)

%.o: %.cpp
   $(MCC) $< -o $@ $(INCLUDE)

clean:     
   rm -f *.o $(EXE) core 
